"""Provider configuration, model aliases, and constants."""

from __future__ import annotations

import os

PROVIDER_TIMEOUT = int(os.getenv("PROVIDER_TIMEOUT", "180"))
PORT = int(os.getenv("PORT", "8080"))

PROVIDERS: dict[str, dict[str, str]] = {
    "pollinations": {
        "base_url": "https://gen.pollinations.ai/v1",
        "api_key": os.getenv("POLLINATIONS_API_KEY", "pk_i0NJnRMi1nHDjerf"),
    },
    "deepinfra": {
        "base_url": "https://api.deepinfra.com/v1/openai",
    },
}

MODEL_PROVIDER_MAP: dict[str, list[str]] = {
    "openai": ["pollinations"],
    "gpt": ["pollinations", "deepinfra"],
    "deepseek": ["deepinfra", "pollinations"],
    "claude": ["pollinations"],
    "gemini": ["pollinations"],
    "llama": ["pollinations"],
    "qwen": ["pollinations"],
    "qwen3.5": ["deepinfra", "pollinations"],
    "kimi": ["deepinfra", "pollinations"],
    "mistral": ["pollinations"],
    "nemotron": ["deepinfra", "pollinations"],
    "step": ["deepinfra", "pollinations"],
    "glm": ["pollinations"],
    "mixtral": ["pollinations"],
    "gemma": ["pollinations"],
    "grok": ["pollinations"],
    "perplexity": ["pollinations"],
    "nova": ["pollinations"],
    "minimax": ["pollinations"],
    "midijourney": ["pollinations"],
}

MODEL_ALIASES: dict[str, str] = {
    "gpt-4o": "openai",
    "gpt-4.1": "openai",
    "gpt-5": "openai",
    "gpt-5.4": "gpt",
    "gpt-5.4-reasoning": "gpt",
    "gpt-5.4-nano": "openai",
    "gpt-5.4-mini": "gpt",
    "gpt-5.5": "gpt",
    "gpt-5.5-reasoning": "gpt",
    "openai-large": "gpt",
    "openai-reasoning": "gpt",
    "deepseek": "deepseek",
    "deepseek-v3": "deepseek",
    "deepseek-v4": "deepseek",
    "deepseek-v4-flash": "deepseek",
    "deepseek-v4-pro": "deepseek",
    "deepseek-r1": "deepseek",
    "deepseek-pro": "deepseek",
    "claude": "claude",
    "claude-4": "claude",
    "claude-haiku": "claude",
    "claude-sonnet": "claude",
    "claude-sonnet-4.6": "claude",
    "claude-opus": "claude",
    "claude-opus-4.6": "claude",
    "claude-opus-4.7": "claude",
    "gemini": "gemini",
    "gemini-2.5-flash": "gemini",
    "gemini-3-flash": "gemini",
    "gemini-3.5-flash": "gemini",
    "gemini-flash-lite-3.1": "gemini",
    "gemini-flash-lite": "gemini",
    "gemini-search": "gemini",
    "llama": "llama",
    "llama-maverick": "llama",
    "llama-scout": "llama",
    "llama-3.3": "llama",
    "qwen-3.5-122b": "qwen3.5",
    "qwen3.5-122b": "qwen3.5",
    "glm": "glm",
    "glm-5": "glm",
    "glm-5.1": "glm",
    "kimi": "kimi",
    "kimi-k2.5": "kimi",
    "kimi-k2.6": "kimi",
    "nemotron-super": "nemotron",
    "nemotron-3-super": "nemotron",
    "minimax": "minimax",
    "minimax-m2.7": "minimax",
    "mistral": "mistral",
    "mistral-4": "mistral",
    "mistral-large": "mistral",
    "mistral-small": "mistral",
    "qwen-coder": "qwen",
    "qwen-large": "qwen",
    "qwen-vision": "qwen",
    "qwen-vision-pro": "qwen",
    "qwen-coder-large": "qwen",
    "qwen-safety": "qwen",
    "grok": "grok",
    "grok-large": "grok",
    "grok-fast": "grok",
    "step-3.5": "step",
    "step-3.5-flash": "step",
    "perplexity-fast": "perplexity",
    "perplexity-reasoning": "perplexity",
    "sonar": "perplexity",
    "nova-fast": "nova",
    "nova": "nova",
    "gemma": "gemma",
    "gemma-4": "gemma",
    "midijourney": "midijourney",
}
